version: "3.9"
services:
  preview:
    image: gcr.io/cloud-tagging-10302018/gtm-cloud-image:stable
    restart: always
    environment:
     - RUN_AS_PREVIEW_SERVER=true
     - CONTAINER_CONFIG=<put google config string here>
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.preview.loadbalancer.server.port=8080"
      - "traefik.http.routers.preview.rule=Host(`analytics.example.com`)"
      - "traefik.http.routers.preview.entrypoints=websecure"
      - "traefik.http.routers.preview.tls.certresolver=myresolver"
  sst:
    image: gcr.io/cloud-tagging-10302018/gtm-cloud-image:stable
    restart: always
    environment:
     - CONTAINER_CONFIG=<put google config string here>
     - PRREVIEW_SERVER_URL=https://analytics.example.com
#    ports:
#      - "8081:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.sst.loadbalancer.server.port=8080"
      - "traefik.http.routers.sst.rule=Host(`gtm.example.com`)"
      - "traefik.http.routers.sst.entrypoints=websecure"
      - "traefik.http.routers.sst.tls.certresolver=myresolver"
  traefik:
    # The official v2 Traefik docker image
    image: "traefik:v2.2"
    container_name: "traefik"
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=<your e-mail>"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
       - "80:80"
       - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
